<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Dalamud.NET.Sdk/15.0.0">
  <PropertyGroup>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <Version>0.1.0.0</Version>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <IsPackable>false</IsPackable>
    <Name>Twenty One</Name>
    <Author>HaySidney</Author>
    <Punchline>Run a Blackjack table in your FFXIV venue.</Punchline>
    <Description>Facilitates Blackjack games via Chat. Type /twentyone to open the table.</Description>
    <Tags>Blackjack;Black Jack;Cards;Dealer;Croupier;Casino;Venue;Game</Tags>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="SonarAnalyzer.CSharp" Version="*">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
    </PackageReference>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\TwentyOne.Game\TwentyOne.Game.csproj" />
  </ItemGroup>
</Project>
